openRin/Rin

client/.env.example
client/src/page/feeds.tsx
docs/DEPLOY.md
docs/ENV.md
server/src/services/feed.ts

feat: Add pagination support

---

client/src/App.tsx
client/src/components/header.tsx
client/src/index.css
client/src/page/timeline.tsx
server/src/services/feed.ts

feat: add timeline support
solve #23

feat: add timeline support

---

docs/DEPLOY.md
docs/ENV.md
scripts/migrator.ts
server/.env.test
server/src/db/db.ts
server/src/setup.ts

* by add `RIN_` prefix，now `GITHUB_CLIENT_ID` is `RIN_GITHUB_CLIENT_ID`, `GITHUB_CLIENT_SECRET` is `RIN_GITHUB_CLIENT_SECRET`

fix: can not add env start with `GITHUB_`

---

client/index.html
client/src/main.tsx
client/src/page/feed.tsx
client/src/utils/constants.ts

Remove the hardcoded page title "Xeu" from index.html and add the dynamic page title using the siteName constant in main.tsx.

chore: Update page title in index.html and main.tsx

---

README_zh_CN.md

docs: add english README.md

---

client/src/page/feed.tsx

style: Update comment layout and styling

---

.github/workflows/deploy.yaml
.github/workflows/seo.yaml
scripts/migrator.ts
scripts/render.ts
server/src/db/db.ts
server/src/services/storage.ts
wrangler.example.toml

deploy测试过了，没问题
seo运行成功，暂时不知道怎么测试，爬虫是能保存到图片的
按照issue中的指导，不过我采用了：
const forcePathStyle = env.S3_FORCE_PATH_STYLE === "true";
而不是const forcePathStyle = env.S3_FORCE_PATH_STYLE === "1" || false;
在migrator.ts中已经有默认值的情况下 || false有什么其他原因吗？
另外使用了我感觉更加直观的true

Add S3_FORCE_PATH_STYLE

---

server/src/services/storage.ts

fix: unused forcePathStyle

---

client/src/components/footer.tsx
client/src/components/header.tsx
client/src/index.css
client/src/page/friends.tsx
client/src/page/writing.tsx

feat: support menu on mobile

---

client/src/components/padding.tsx
client/src/page/feeds.tsx
client/src/page/friends.tsx
client/src/page/timeline.tsx

feat: add friend edit and delete support

---

client/package.json
client/src/App.tsx
client/src/components/header.tsx
client/src/index.css
client/src/page/feed.tsx
client/src/vite-env.d.ts

feat: add TOC support

---

client/src/components/loading.tsx
client/src/page/feed.tsx
client/src/page/feeds.tsx
client/src/page/friends.tsx
client/src/page/timeline.tsx

fix: friends list shuffled running everytime

feat: Update Waiting component props in multiple files

---

client/src/App.tsx
client/src/components/header.tsx
client/src/page/feeds.tsx
client/src/page/writing.tsx
client/src/utils/int.ts

* also fix frozen bug when switching page by menu on mobile phone

fix: update writing page style

---

client/package.json

* fix workspace version https://bun.sh/blog/bun-v1.1.13#fixed-aliased-workspace-dependencies-fix

ci: bump bun to v1.1.13

---

client/.env.example
client/src/App.tsx
client/src/components/header.tsx
client/src/main.tsx
client/src/page/settings.tsx
docs/ENV.md
package.json
server/package.json
server/src/services/feed.ts
server/src/services/user.ts

feat: add WordPress import support

---

client/index.html
client/src/components/markdown.tsx
client/src/index.css
client/src/page/feed.tsx
client/src/page/writing.tsx
client/src/utils/darkModeUtils.ts
package.json

替换了原来的markdownPreview组件为react-markdown，并使用rehype-katex来渲染katex

使用react-markdown支持了katex的渲染

---

.github/workflows/deploy.yaml
client/package.json
client/src/App.tsx
client/src/components/footer.tsx
client/src/index.css
client/src/page/settings.tsx
client/src/page/writing.tsx
client/src/state/config.tsx
client/src/utils/thumb.css
package.json
server/package.json
server/src/_worker.ts
server/src/server.ts
server/src/services/comments.ts
server/src/services/config.ts
server/src/services/feed.ts
server/src/services/friends.ts
server/src/services/rss.ts
server/src/services/seo.ts
server/src/services/storage.ts
server/src/services/tag.ts
server/src/services/user.ts
server/src/setup.ts
server/src/utils/cache.ts
server/src/utils/config.ts
server/src/utils/di.ts
server/src/utils/s3.ts
server/tsconfig.json

feat: add dynamic config support

---

client/.gitignore
client/i18next-parser.config.js
client/package.json
client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/src/components/feed_card.tsx
client/src/components/header.tsx
client/src/utils/timeago.ts
package.json

feat: add i18n(ja) support

---

client/.gitignore
client/i18next-parser.config.js
client/package.json
client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/src/components/feed_card.tsx
client/src/components/header.tsx
client/src/page/writing.tsx
client/src/utils/timeago.ts
package.json
server/src/utils/cache.ts

fix: bad translation hook & bad cache load logic

---

client/.gitignore
client/i18next-parser.config.js
client/package.json
client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/src/components/feed_card.tsx
client/src/components/header.tsx
client/src/components/markdown.tsx
client/src/page/feed.tsx
client/src/page/feeds.tsx
client/src/page/writing.tsx
client/src/utils/timeago.ts
package.json
server/src/services/feed.ts
server/src/services/friends.ts
server/src/utils/cache.ts

fix: error cache key

---

server/src/services/feed.ts

fix: alias cache clear policy

---

client/src/page/feed.tsx

feat: more satisfying interface and some hover effect

---

README.md
client/package.json
client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/public/locales/zh/translation.json
client/src/components/footer.tsx
client/src/components/header.tsx
client/src/page/writing.tsx
client/src/utils/darkModeUtils.ts
server/src/services/feed.ts

feat: new monaco editor

---

client/src/base.css
client/src/components.css
client/src/components/footer.tsx
client/src/components/header.tsx
client/src/components/markdown.tsx
client/src/index.css
client/src/main.tsx
client/src/page/writing.tsx
server/src/services/storage.ts

* fix #173 
* fix #169 
* partially fix #165

fix: a bunch of bugs

---

client/src/page/friends.tsx

fix: incorrect style

---

client/package.json
client/src/components/markdown.tsx
client/src/index.css

feat: add callout support

---

client/src/components/markdown.tsx

feat: add copy support for code block

---

client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/public/locales/zh/translation.json
client/src/App.tsx
client/src/components/hashtag.tsx
client/src/components/header.tsx
client/src/components/markdown.tsx
client/src/page/hashtag.tsx
client/src/page/hashtags.tsx
server/src/services/tag.ts

feat: add hashtag page support

---

client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/public/locales/zh/translation.json
client/src/components/button.tsx
client/src/components/dialog.tsx
client/src/page/feed.tsx
client/src/page/friends.tsx
client/src/page/settings.tsx
client/src/page/writing.tsx
server/src/services/friends.ts

feat: new alert support

---

client/package.json
client/src/components/markdown.tsx

feat: add image lightbox

---

client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/public/locales/zh/translation.json
client/src/App.tsx
client/src/components/footer.tsx
client/src/main.tsx
client/src/page/feed.tsx
client/src/page/friends.tsx
client/src/page/settings.tsx
client/src/state/config.tsx
server/sql/0001.sql
server/src/db/schema.ts
server/src/services/feed.ts

 feat: add visit count support 

---

client/src/App.tsx
client/src/components/markdown.tsx
client/src/hooks/useTableOfContents.tsx
client/src/page/feed.tsx

* also fix #201 
* [fix: broken image lightbox](https://github.com/OXeu/Rin/commit/b6d10725cbb1bea35f33784576ebac6cfca0e6f2)
* [fix: scroll bias in index jumps](https://github.com/OXeu/Rin/commit/333b52a69370d9a92fefe04303f0c66363d7df9c)

fix: a few known bugs

---

client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/public/locales/zh/translation.json
client/src/App.tsx
client/src/base.css
client/src/components/feed_card.tsx
client/src/components/header.tsx
client/src/components/input.tsx
client/src/page/feed.tsx
client/src/page/search.tsx
client/src/page/writing.tsx
server/sql/0002.sql
server/src/db/schema.ts
server/src/services/feed.ts
server/src/services/friends.ts

feat: #139 feature request

---

server/src/services/rss.ts

@OXeu RT;
issues https://github.com/openRin/Rin/issues/228

fix: processing S3_ACCESS_HOST configuration without protocol header 

---

package.json
server/src/_worker.ts

fix: rss crontab exception

---

client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/public/locales/zh-CN/translation.json
client/public/locales/zh-TW/translation.json
client/src/components/adjacent_feed.tsx
client/src/components/feed_card.tsx
client/src/page/callback.tsx
client/src/page/feed.tsx
client/src/page/settings.tsx
client/src/page/timeline.tsx
server/src/services/feed.ts
server/src/utils/cache.ts

feat: Add adjacent feeds feature (Closes #202)

---

client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/public/locales/zh-CN/translation.json
client/public/locales/zh-TW/translation.json
client/src/page/friends.tsx
server/sql/0003.sql
server/src/db/schema.ts
server/src/services/friends.ts

feat: Add sorting for friend list

---

client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/public/locales/zh-CN/translation.json
client/public/locales/zh-TW/translation.json
client/src/App.tsx
client/src/components/footer.tsx
client/src/components/header.tsx
client/src/components/markdown_editor.tsx
client/src/components/moment_item.tsx
client/src/page/moments.tsx
client/src/page/writing.tsx
server/sql/0004.sql
server/src/db/schema.ts
server/src/server.ts
server/src/services/moments.ts

This PR introduces Moments module that allows users to publish and view short-form posts (a.k.a. “动态” or “说说”). 
The current design uses a card-based layout, but it may be refined in the future to adopt the timeline style proposed in issue #232.
In addition, image display style needs further optimization, and dedicated, styled embed cards could be introduced for popular external links(online music/video platforms etc.) to enhance their presentation.
close #232

feat: add Moments feature

---

client/public/locales/en/translation.json
client/public/locales/ja/translation.json
client/public/locales/zh-CN/translation.json
client/public/locales/zh-TW/translation.json
client/src/App.tsx
client/src/page/error.tsx

Add ErrorPage component, apply route guards to /writing and /settings, and render a 404 page for unmatched routes.
fix #303

feat: add router guard for settings and writing
